const products = [{
        img: 'assets/picturesForProductsList/Metro-Exodus.jpg',
        title: 'Metro-Exodus',
        price: 25.99,
        discount: 30,
        inCart: 0,
    }, {
        img: 'assets/picturesForProductsList/PathfinderWrathoftheRighteousMythicEdition.jpg',
        title: 'Pathfinder Wrath of the Righteous - Mythic Edition',
        price: 54.99,
        discount: 15,
        inCart: 0,
        relizeDate: '01.09.2021',
        productPage: 'productPage.html',
    }, {
        img: 'assets/picturesForProductsList/SyberiaTheWorldBefore.jpg',
        title: 'Syberia The World Before',
        price: 20.99,
        discount: 25,
        inCart: 0,
    }, {
        img: 'assets/picturesForProductsList/Subverse.jpg',
        title: 'Subverse',
        price: 19.99,
        discount: 30,
        inCart: 0,
    }, {
        img: 'assets/picturesForProductsList/ShadowWarrior3.jpg',
        title: 'Shadow Warrior 3',
        price: 27.99,
        discount: 20,
        inCart: 0,
    },
    {
        img: 'assets/picturesForProductsList/BaldursGateIII.jpg',
        title: 'Baldurs Gate III',
        price: 25,
        discount: 5,
        inCart: 0,
    },
    {
        img: 'assets/picturesForProductsList/divinityoriginalsin2definitive.jpg',
        title: 'Divinity Original Sin 2 Definitive',
        price: 35.50,
        discount: 10,
        inCart: 0,
    },
    {
        img: 'assets/picturesForProductsList/DragonsDogmaDarkArisen.jpg',
        title: 'Dragons Dogma Dark Arisen',
        price: 20.45,
        discount: 17,
        inCart: 0,
    },
    {
        img: 'assets/picturesForProductsList/greedfall.jpg',
        title: 'Greed Fall',
        price: 15.75,
        discount: 5,
        inCart: 0,
    },
]